#!/usr/bin/env bash
# Configure ubuntu container to listen on port 80
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sities-available/default /etc/nginx/sites-enabled/default
kill "$(pgrep 'nginx' | head -1)"
