#!/usr/bin/env bash
#This script displays
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash

filenames=$(ls ./)
for filename in "${filenames[@]}"; do
    echo "$filename" | cut -d'-' -f2-
done
